spring:
  profiles:
    active: dev

---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:${mangaserver.database}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true
    show-sql: true

server:
  port: 10033

mangaserver:
  database: database.sqlite

---

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://localhost:5432/mangaserver
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
